"""Attack path models for structured kill chain threat modeling.

These models define the output schema for attack paths generated by the swarm,
ensuring consistent structure across reconnaissance through objective phases.
"""

from typing import List, Optional, Literal
from pydantic import BaseModel, Field


class MitigationDetail(BaseModel):
    """Detailed mitigation for a specific attack step."""

    mitigation_id: str = Field(
        ...,
        description="ATT&CK mitigation ID (e.g., M1048) or custom ID (e.g., CUSTOM-001)",
    )
    mitigation_name: str = Field(
        ...,
        description="Short mitigation name",
    )
    description: str = Field(
        ...,
        description="2-3 sentences describing the specific mitigation action",
    )
    aws_service_action: str = Field(
        ...,
        description="Specific AWS action or service configuration to implement",
    )


class AttackStep(BaseModel):
    """A single step in a kill chain attack path."""

    step_number: int = Field(
        ...,
        ge=1,
        le=5,
        description="Step number in the kill chain (1-5)",
    )
    kill_chain_phase: Literal[
        "Reconnaissance",
        "Initial Access",
        "Execution & Persistence",
        "Lateral Movement & Privilege Escalation",
        "Objective (Exfiltration/Impact)",
        "Covering Tracks",
    ] = Field(
        ...,
        description="Kill chain phase for this step",
    )
    technique_id: str = Field(
        ...,
        description="MITRE ATT&CK technique ID (e.g., T1190)",
    )
    technique_name: str = Field(
        ...,
        description="Human-readable technique name",
    )
    target_asset: str = Field(
        ...,
        description="Specific asset from the asset graph being targeted",
    )
    action_description: str = Field(
        ...,
        description="2-3 sentences describing what the attacker does at this step",
    )
    outcome: str = Field(
        ...,
        description="What the attacker gains from this step that enables the next step",
    )
    mitigation: Optional[MitigationDetail] = Field(
        default=None,
        description="Mitigation detail for this step",
    )


class AttackPath(BaseModel):
    """A complete end-to-end attack path following the cyber kill chain."""

    id: str = Field(
        default="",
        description="Unique identifier for the attack path",
    )
    name: str = Field(
        ...,
        description="Descriptive attack scenario name",
    )
    objective: str = Field(
        ...,
        description="The attacker's end goal in one sentence",
    )
    threat_actor: str = Field(
        ...,
        description="Which persona generated this path",
    )
    impact_type: Literal["confidentiality", "integrity", "availability"] = Field(
        ...,
        description="Primary impact type",
    )
    difficulty: Literal["low", "medium", "high"] = Field(
        ...,
        description="Overall difficulty rating",
    )
    steps: List[AttackStep] = Field(
        ...,
        min_items=3,
        max_items=5,
        description="Kill chain steps (3-5 steps)",
    )
    composite_score: Optional[float] = Field(
        default=None,
        description="Composite evaluation score from evaluation swarm",
    )
    confidence: Optional[Literal["high", "medium", "low"]] = Field(
        default=None,
        description="Confidence rating from adversarial swarm",
    )
    challenged: bool = Field(
        default=False,
        description="Whether blue team challenged this path",
    )
    challenge_resolution: Optional[str] = Field(
        default=None,
        description="Resolution of blue team challenge",
    )
    validation_notes: Optional[str] = Field(
        default=None,
        description="Validation notes from arbitrator",
    )
    evaluation: Optional[dict] = Field(
        default=None,
        description="Detailed evaluation scores",
    )
